[meta]
name = "GhostToReplay"
author = "skybaxrider"
category = "Race"
blocks = [ "Plugin_GhostToReplay" ]
siteid = 62
version = "1.1"

[script]
imports = [ "Icons.as", "Formatting.as", "Time.as" ]
